### ISSUE TITLE
模块中的delegate不能创建问题

### ISSUE THREAD

**Issue by BaqideID** [cr330326/DemoComponent#1]
c-framework模块中的ModuleManager中的loadModule()方法，为delegateNameList添加数据的时候应该是moduleInfo的delegateName，现在写的是包名，导致反射时不能创建类

**Comment by cr330326** [comment]
> c-framework模块中的ModuleManager中的loadModule()方法，为delegateNameList添加数据的时候应该是moduleInfo的delegateName，现在写的是包名，导致反射时不能创建类

那个包名内部会去遍历整个dex中符合包名的实现类，或者可以试试用具体类的包名路径当参数传入，省去遍历寻找过程。
